name = "kusama"
genesis_hash = "b0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe"
default_url = "wss://kusama-rpc.polkadot.io:443"
spec_change_blocks = [0]

[custom_keys]
amount = "u128"
cycle_block = "u32"
cycle_period = "u32"
hash = "bytes32"
index = "u32"
kept = "u128"
message_id = "bytes32"
migrated = "u128"
num_pure_accounts = "u32"
poll = "u32"
prioritized = "bool"
query_id = "u64"
up_to = "u32"
votes = "u32"

[[pallets]]
name = "System"
sdk = true

[[pallets]]
name = "Indices"
sdk = true

[[pallets]]
name = "Balances"
sdk = true

[[pallets]]
name = "TransactionPayment"
sdk = true

[[pallets]]
name = "Staking"
sdk = true

[[pallets]]
name = "Offences"
events = [
  { name = "Offence" },
]

[[pallets]]
name = "Historical"
events = [
  { name = "RootStored", params = [
    { field = "index", key = "index" },
  ] },
  { name = "RootsPruned", params = [
    { field = "up_to", key = "up_to" },
  ] },
]

[[pallets]]
name = "Session"
sdk = true

[[pallets]]
name = "Grandpa"
sdk = true

[[pallets]]
name = "Treasury"
sdk = true

[[pallets]]
name = "ConvictionVoting"
sdk = true

[[pallets]]
name = "Referenda"
sdk = true

[[pallets]]
name = "FellowshipCollective"
events = [
  { name = "MemberAdded", params = [
    { field = "who", key = "account_id" },
  ] },
  { name = "RankChanged", params = [
    { field = "who", key = "account_id" },
  ] },
  { name = "MemberRemoved", params = [
    { field = "who", key = "account_id" },
  ] },
  { name = "Voted", params = [
    { field = "who", key = "account_id" },
    { field = "poll", key = "poll" },
  ] },
  { name = "MemberExchanged", params = [
    { field = "who", key = "account_id" },
    { field = "new_who", key = "account_id" },
  ] },
]

[[pallets]]
name = "FellowshipReferenda"
events = [
  { name = "Submitted", params = [
    { field = "index", key = "index" },
  ] },
  { name = "DecisionDepositPlaced", params = [
    { field = "index", key = "index" },
    { field = "who", key = "account_id" },
    { field = "amount", key = "amount" },
  ] },
  { name = "DecisionDepositRefunded", params = [
    { field = "index", key = "index" },
    { field = "who", key = "account_id" },
    { field = "amount", key = "amount" },
  ] },
  { name = "DepositSlashed", params = [
    { field = "who", key = "account_id" },
    { field = "amount", key = "amount" },
  ] },
  { name = "DecisionStarted", params = [
    { field = "index", key = "index" },
  ] },
  { name = "ConfirmStarted", params = [
    { field = "index", key = "index" },
  ] },
  { name = "ConfirmAborted", params = [
    { field = "index", key = "index" },
  ] },
  { name = "Confirmed", params = [
    { field = "index", key = "index" },
  ] },
  { name = "Approved", params = [
    { field = "index", key = "index" },
  ] },
  { name = "Rejected", params = [
    { field = "index", key = "index" },
  ] },
  { name = "TimedOut", params = [
    { field = "index", key = "index" },
  ] },
  { name = "Cancelled", params = [
    { field = "index", key = "index" },
  ] },
  { name = "Killed", params = [
    { field = "index", key = "index" },
  ] },
  { name = "SubmissionDepositRefunded", params = [
    { field = "index", key = "index" },
    { field = "who", key = "account_id" },
    { field = "amount", key = "amount" },
  ] },
  { name = "MetadataSet", params = [
    { field = "index", key = "index" },
    { field = "hash", key = "hash" },
  ] },
  { name = "MetadataCleared", params = [
    { field = "index", key = "index" },
    { field = "hash", key = "hash" },
  ] },
]

[[pallets]]
name = "Whitelist"
sdk = true

[[pallets]]
name = "Parameters"
sdk = true

[[pallets]]
name = "Claims"
events = [
  { name = "Claimed", params = [
    { field = "who", key = "account_id" },
    { field = "amount", key = "amount" },
  ] },
]

[[pallets]]
name = "Utility"
sdk = true

[[pallets]]
name = "Society"
sdk = true

[[pallets]]
name = "Recovery"
sdk = true

[[pallets]]
name = "Vesting"
sdk = true

[[pallets]]
name = "Scheduler"
sdk = true

[[pallets]]
name = "Proxy"
sdk = true

[[pallets]]
name = "Multisig"
sdk = true

[[pallets]]
name = "Preimage"
sdk = true

[[pallets]]
name = "Bounties"
sdk = true

[[pallets]]
name = "ChildBounties"
sdk = true

[[pallets]]
name = "ElectionProviderMultiPhase"
sdk = true

[[pallets]]
name = "VoterList"
sdk = true

[[pallets]]
name = "NominationPools"
sdk = true

[[pallets]]
name = "FastUnstake"
sdk = true

[[pallets]]
name = "DelegatedStaking"
sdk = true

[[pallets]]
name = "StakingAhClient"
sdk = true

[[pallets]]
name = "ParaInclusion"
sdk = true

[[pallets]]
name = "Paras"
sdk = true

[[pallets]]
name = "Hrmp"
sdk = true

[[pallets]]
name = "ParasDisputes"
sdk = true

[[pallets]]
name = "OnDemandAssignmentProvider"
sdk = true

[[pallets]]
name = "Registrar"
sdk = true

[[pallets]]
name = "Slots"
sdk = true

[[pallets]]
name = "Auctions"
sdk = true

[[pallets]]
name = "Crowdloan"
sdk = true

[[pallets]]
name = "Coretime"
sdk = true

[[pallets]]
name = "XcmPallet"
sdk = true

[[pallets]]
name = "MessageQueue"
sdk = true

[[pallets]]
name = "AssetRate"
sdk = true

[[pallets]]
name = "RcMigrator"
events = [
  { name = "StageTransition", params = [
    { field = "old", key = "account_id" },
    { field = "new", key = "account_id" },
  ] },
  { name = "AssetHubMigrationStarted" },
  { name = "AssetHubMigrationFinished" },
  { name = "QueryResponseReceived", params = [
    { field = "query_id", key = "query_id" },
  ] },
  { name = "XcmResendAttempt", params = [
    { field = "query_id", key = "query_id" },
  ] },
  { name = "UnprocessedMsgBufferSet", params = [
    { field = "new", key = "account_id" },
    { field = "old", key = "account_id" },
  ] },
  { name = "AhUmpQueuePrioritySet", params = [
    { field = "prioritized", key = "prioritized" },
    { field = "cycle_block", key = "cycle_block" },
    { field = "cycle_period", key = "cycle_period" },
  ] },
  { name = "AhUmpQueuePriorityConfigSet", params = [
    { field = "old", key = "account_id" },
    { field = "new", key = "account_id" },
  ] },
  { name = "MigratedBalanceRecordSet", params = [
    { field = "kept", key = "kept" },
    { field = "migrated", key = "migrated" },
  ] },
  { name = "MigratedBalanceConsumed", params = [
    { field = "kept", key = "kept" },
    { field = "migrated", key = "migrated" },
  ] },
  { name = "ManagerSet", params = [
    { field = "old", key = "account_id" },
    { field = "new", key = "account_id" },
  ] },
  { name = "XcmSent", params = [
    { field = "message_id", key = "message_id" },
  ] },
  { name = "StakingElectionsPaused" },
  { name = "AccountsPreserved", params = [
    { field = "accounts", key = "account_id", multi = true },
  ] },
  { name = "CancellerSet", params = [
    { field = "old", key = "account_id" },
    { field = "new", key = "account_id" },
  ] },
  { name = "MigrationPaused" },
  { name = "MigrationCancelled" },
  { name = "PureAccountsIndexed", params = [
    { field = "num_pure_accounts", key = "num_pure_accounts" },
  ] },
  { name = "ManagerMultisigDispatched" },
  { name = "ManagerMultisigVoted", params = [
    { field = "votes", key = "votes" },
  ] },
  { name = "MigrationSettingsSet", params = [
    { field = "old", key = "account_id" },
    { field = "new", key = "account_id" },
  ] },
]
