name = "paseo"
genesis_hash = "77afd6190f1554ad45fd0d31aee62aacc33c6db0ea801129acb813f913e0764f"
default_url = "wss://paseo.ibp.network:443"
versions = [0]

[custom_keys]
amount = "u128"
cycle_block = "u32"
cycle_period = "u32"
index = "u32"
kept = "u128"
message_id = "bytes32"
migrated = "u128"
num_pure_accounts = "u32"
prioritized = "bool"
query_id = "u64"
up_to = "u32"
votes = "u32"

[[pallets]]
name = "System"
sdk = true

[[pallets]]
name = "Scheduler"
sdk = true

[[pallets]]
name = "Preimage"
sdk = true

[[pallets]]
name = "Indices"
sdk = true

[[pallets]]
name = "Balances"
sdk = true

[[pallets]]
name = "TransactionPayment"
sdk = true

[[pallets]]
name = "Staking"
sdk = true

[[pallets]]
name = "Offences"
events = [
  { name = "Offence" },
]

[[pallets]]
name = "Historical"
events = [
  { name = "RootStored", params = [
    { field = "index", key = "index" },
  ] },
  { name = "RootsPruned", params = [
    { field = "up_to", key = "up_to" },
  ] },
]

[[pallets]]
name = "Session"
sdk = true

[[pallets]]
name = "Grandpa"
sdk = true

[[pallets]]
name = "Treasury"
sdk = true

[[pallets]]
name = "ConvictionVoting"
sdk = true

[[pallets]]
name = "Referenda"
sdk = true

[[pallets]]
name = "Whitelist"
sdk = true

[[pallets]]
name = "Claims"
events = [
  { name = "Claimed", params = [
    { field = "who", key = "account_id" },
    { field = "amount", key = "amount" },
  ] },
]

[[pallets]]
name = "Vesting"
sdk = true

[[pallets]]
name = "Utility"
sdk = true

[[pallets]]
name = "Proxy"
sdk = true

[[pallets]]
name = "Multisig"
sdk = true

[[pallets]]
name = "Bounties"
sdk = true

[[pallets]]
name = "ChildBounties"
sdk = true

[[pallets]]
name = "ElectionProviderMultiPhase"
sdk = true

[[pallets]]
name = "VoterList"
sdk = true

[[pallets]]
name = "NominationPools"
sdk = true

[[pallets]]
name = "FastUnstake"
sdk = true

[[pallets]]
name = "DelegatedStaking"
sdk = true

[[pallets]]
name = "StakingAhClient"
sdk = true

[[pallets]]
name = "ParaInclusion"
sdk = true

[[pallets]]
name = "Paras"
sdk = true

[[pallets]]
name = "Hrmp"
sdk = true

[[pallets]]
name = "ParasDisputes"
sdk = true

[[pallets]]
name = "OnDemand"
sdk = true

[[pallets]]
name = "Registrar"
sdk = true

[[pallets]]
name = "Slots"
sdk = true

[[pallets]]
name = "Auctions"
sdk = true

[[pallets]]
name = "Crowdloan"
sdk = true

[[pallets]]
name = "Coretime"
sdk = true

[[pallets]]
name = "StateTrieMigration"
sdk = true

[[pallets]]
name = "XcmPallet"
sdk = true

[[pallets]]
name = "MessageQueue"
sdk = true

[[pallets]]
name = "AssetRate"
sdk = true

[[pallets]]
name = "Sudo"
sdk = true

[[pallets]]
name = "RcMigrator"
events = [
  { name = "StageTransition", params = [
    { field = "old", key = "account_id" },
    { field = "new", key = "account_id" },
  ] },
  { name = "AssetHubMigrationStarted" },
  { name = "AssetHubMigrationFinished" },
  { name = "QueryResponseReceived", params = [
    { field = "query_id", key = "query_id" },
  ] },
  { name = "XcmResendAttempt", params = [
    { field = "query_id", key = "query_id" },
  ] },
  { name = "UnprocessedMsgBufferSet", params = [
    { field = "new", key = "account_id" },
    { field = "old", key = "account_id" },
  ] },
  { name = "AhUmpQueuePrioritySet", params = [
    { field = "prioritized", key = "prioritized" },
    { field = "cycle_block", key = "cycle_block" },
    { field = "cycle_period", key = "cycle_period" },
  ] },
  { name = "AhUmpQueuePriorityConfigSet", params = [
    { field = "old", key = "account_id" },
    { field = "new", key = "account_id" },
  ] },
  { name = "MigratedBalanceRecordSet", params = [
    { field = "kept", key = "kept" },
    { field = "migrated", key = "migrated" },
  ] },
  { name = "MigratedBalanceConsumed", params = [
    { field = "kept", key = "kept" },
    { field = "migrated", key = "migrated" },
  ] },
  { name = "ManagerSet", params = [
    { field = "old", key = "account_id" },
    { field = "new", key = "account_id" },
  ] },
  { name = "XcmSent", params = [
    { field = "message_id", key = "message_id" },
  ] },
  { name = "StakingElectionsPaused" },
  { name = "AccountsPreserved", params = [
    { field = "accounts", key = "account_id", multi = true },
  ] },
  { name = "CancellerSet", params = [
    { field = "old", key = "account_id" },
    { field = "new", key = "account_id" },
  ] },
  { name = "MigrationPaused" },
  { name = "MigrationCancelled" },
  { name = "PureAccountsIndexed", params = [
    { field = "num_pure_accounts", key = "num_pure_accounts" },
  ] },
  { name = "ManagerMultisigDispatched" },
  { name = "ManagerMultisigVoted", params = [
    { field = "votes", key = "votes" },
  ] },
  { name = "MigrationSettingsSet", params = [
    { field = "old", key = "account_id" },
    { field = "new", key = "account_id" },
  ] },
]
