name = "westend"
genesis_hash = "e143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e"
default_url = "wss://westend-rpc.polkadot.io:443"
spec_change_blocks = [0]

[custom_keys]
identity = "u128"
index = "u32"
migrations = "u32"
subs = "u128"
took = "u32"
up_to = "u32"

[[pallets]]
name = "System"
sdk = true

[[pallets]]
name = "Indices"
sdk = true

[[pallets]]
name = "Balances"
sdk = true

[[pallets]]
name = "TransactionPayment"
sdk = true

[[pallets]]
name = "Staking"
sdk = true

[[pallets]]
name = "Offences"
events = [
  { name = "Offence" },
]

[[pallets]]
name = "Historical"
events = [
  { name = "RootStored", params = [
    { field = "index", key = "index" },
  ] },
  { name = "RootsPruned", params = [
    { field = "up_to", key = "up_to" },
  ] },
]

[[pallets]]
name = "Parameters"
sdk = true

[[pallets]]
name = "Session"
sdk = true

[[pallets]]
name = "Grandpa"
sdk = true

[[pallets]]
name = "Utility"
sdk = true

[[pallets]]
name = "Identity"
sdk = true

[[pallets]]
name = "Recovery"
sdk = true

[[pallets]]
name = "Vesting"
sdk = true

[[pallets]]
name = "Scheduler"
sdk = true

[[pallets]]
name = "Preimage"
sdk = true

[[pallets]]
name = "Sudo"
sdk = true

[[pallets]]
name = "Proxy"
sdk = true

[[pallets]]
name = "Multisig"
sdk = true

[[pallets]]
name = "ElectionProviderMultiPhase"
sdk = true

[[pallets]]
name = "VoterList"
sdk = true

[[pallets]]
name = "NominationPools"
sdk = true

[[pallets]]
name = "FastUnstake"
sdk = true

[[pallets]]
name = "ConvictionVoting"
sdk = true

[[pallets]]
name = "Referenda"
sdk = true

[[pallets]]
name = "Whitelist"
sdk = true

[[pallets]]
name = "Treasury"
sdk = true

[[pallets]]
name = "DelegatedStaking"
sdk = true

[[pallets]]
name = "ParaInclusion"
sdk = true

[[pallets]]
name = "Paras"
sdk = true

[[pallets]]
name = "Hrmp"
sdk = true

[[pallets]]
name = "ParasDisputes"
sdk = true

[[pallets]]
name = "OnDemandAssignmentProvider"
sdk = true

[[pallets]]
name = "Registrar"
sdk = true

[[pallets]]
name = "Slots"
sdk = true

[[pallets]]
name = "Auctions"
sdk = true

[[pallets]]
name = "Crowdloan"
sdk = true

[[pallets]]
name = "AssignedSlots"
sdk = true

[[pallets]]
name = "Coretime"
sdk = true

[[pallets]]
name = "StakingAhClient"
sdk = true

[[pallets]]
name = "MultiBlockMigrations"
events = [
  { name = "UpgradeStarted", params = [
    { field = "migrations", key = "migrations" },
  ] },
  { name = "UpgradeCompleted" },
  { name = "UpgradeFailed" },
  { name = "MigrationSkipped", params = [
    { field = "index", key = "index" },
  ] },
  { name = "MigrationAdvanced", params = [
    { field = "index", key = "index" },
    { field = "took", key = "took" },
  ] },
  { name = "MigrationCompleted", params = [
    { field = "index", key = "index" },
    { field = "took", key = "took" },
  ] },
  { name = "MigrationFailed", params = [
    { field = "index", key = "index" },
    { field = "took", key = "took" },
  ] },
  { name = "HistoricCleared" },
]

[[pallets]]
name = "XcmPallet"
sdk = true

[[pallets]]
name = "MessageQueue"
sdk = true

[[pallets]]
name = "AssetRate"
sdk = true

[[pallets]]
name = "RootTesting"
events = [
  { name = "DefensiveTestCall" },
]

[[pallets]]
name = "MetaTx"
sdk = true

[[pallets]]
name = "RootOffences"
sdk = true

[[pallets]]
name = "IdentityMigrator"
events = [
  { name = "IdentityReaped", params = [
    { field = "who", key = "account_id" },
  ] },
  { name = "DepositUpdated", params = [
    { field = "who", key = "account_id" },
    { field = "identity", key = "identity" },
    { field = "subs", key = "subs" },
  ] },
]
